// This file has been auto generated by "compile_resource.py"
#include <stddef.h>

 
#ifndef RESOURCES_H
#define RESOURCES_H
extern const char RESOURCE_DATA_help_txt[];
extern const size_t RESOURCE_SIZE_help_txt;
extern const char RESOURCE_DATA_woof_txt[];
extern const size_t RESOURCE_SIZE_woof_txt;
#endif